### ISSUE TITLE
Message having a field containing char zero causes to throw exception

### ISSUE THREAD

**Issue by maebious** [ANYbotics/variant#3]
Hey,
Using multiplot with msgs that have even one field name containing the zero char '0' at any position  cause multiplot to crash with:  

> terminate called after throwing an instance of 'ros::serialization::StreamOverrunException'
> what():  Buffer Overrun
> Aborted

As far as I can understand the cause of the problem is within this library.
Cheers,
Orestis

**Comment by JiaweiChristy** [comment]
Thank you very much~
It works after I delete Header header from msg file.
