### ISSUE TITLE
Zero in package and message type name not accepted

### ISSUE THREAD

**Issue by fabolhak** [ANYbotics/variant#4]
Hello,
thank you for your great tools 👍. I was using the `rqt_multiplot` plugin. However it was always crashing for some of our messages. I found out that package or message type names containing a `0` are not accepted by [this regex](https://github.com/ethz-asl/variant/blob/master/variant_topic_tools/src/MessageTypeParser.cpp#L28) (only 1-9 are accepted). 

However, in the ROS naming conventions `0`'s as a non-first character are [allowed](http://wiki.ros.org/Names#Valid_Names-1).

**Comment by samuelba** [comment]
Thank you for this bug report, I will look into it and fix it (or you create a pull request).

**Comment by fabolhak** [comment]
I created a PR: https://github.com/ethz-asl/variant/pull/5

**Comment by samuelba** [comment]
Thanks for the fix #5
